spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/test_codebase
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
