spring:
  profiles:
    active: dev # Set the default active profile (can be overridden)
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    filter: true
    try-it-out-enabled: true
    tags-sorter: alpha
  packages-to-scan: com.codebase.controller
logging:
  level:
    org:
      springdoc: info
      springframework: info
app:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080